# Black Jack V1

This bit uses First-visit MC policy to estimate $V \approx v_\pi$  

__Algo:__  
* I use $\epsilon-\text{greedy}$
* state $\in$ {dealer card, count, usable ace}
* action $\in$ {hit, stick}
* Infinite deck is assume

_process:__  
1. two cards to dealer (1 recorded as card up) 
2. two cards to player (ignore card up, not relevent) 
3. If player count <= 11 hit. 
4. Play:
   1. Given state take $\epsilon - \text{greedy action}$ 
   2. Continue to action is stick or bust 
   3. Update $v_\pi$ and $q_\pi$

## Updating $\pi$ and $q_\pi(s,a)$  

Run a simulation to get the following:  
1. final state: (dealer show, count, usable ace) e.g., (4, 22, 0)
2. final reward $\in (-1, 0, 1)$ , e.g.,  -1
3. Final Hand in order, e.g. [9, 1, 10, 2]
   
Evaluate backwards: $G = \gamma G + R_{t+1}$  

Process:  given a final hand ($hand$) for $len(hand) - 2$:  
Initialize: $G = 0, \gamma = 0.9$  
1. State: (4, 20, 0), action = "hit", R = -1
   * $G = \gamma(G) + -1 = 0 - 1 = -1$ 
   * increment $n_{q_\pi}((4,20,0)$ by 1 
   * Update $q_\pi((4,20,0), \text{hit}) = (q_\pi(4,20,0), \text{hit} + G) / n $
   * Update policy $\pi(a|(4,20,0)):
     * Let default value of policy be 0 (for early runs where it is not sampled)  
     * $\pi(a|(4,20,0)) = \arg\max_a(q_\pi(s = (4,20,0), A = a)$
     * set $q_\pi((4,20,0), \text{hit}) = \frac{q_\pi((4,20,0), \text{hit}) + G}{n} $
2. State: (4, 10, 1), action = "hit", R = 0 
   * $G = \gamma(G) + 0 = .9*-1 = -.9$   
   * increment $n_{q_\pi}((4,10,1)$ by 1 
   * Update $q_\pi((4,10,1), \text{hit}) = (q_\pi(4,10,1), \text{hit} + G) / n $
   * Update policy $\pi(a|(4,10,1)):
     * Let default value of policy be 0 (for early runs where it is not sampled)  
     * $\pi(a|(4,10,1)) = \arg\max_a(q_\pi(s = (4,10,1), A = a)$
     * set $q_\pi((4,10,1), \text{hit}) = \frac{q_\pi((4,10,1), \text{hit}) + G}{n} $

In [ ]:
import numpy as np
from numpy import random

In [172]:
policy = {} # a dictionary, key:{dealer card, count, usable ace} value:{hist, stick}
q = {} #The action state value: a dictionary, key:{(dealer card, count, usable ace), action} value:value (G)
q_n = {} # number of times state action pair was touched. same key as above.  value = n touched

In [354]:
def count(cards):
    '''
    Calculate count of hand.
    Returns a tuple (count, usable_ace) 
    usable_ace is binary, 1 if ace is usable Can be counted as 1 to avoid going bust on next hit.  
    There can be only one usable ace.  
    The count is the value of the hand with ace counted as 11 if usable ace or 1 if that would cause bust.  
    '''
    nAces = 0
    usable_ace = 0
    count = 0
    for card in cards:
        if card == 1:
            nAces += 1 
        count += card

    if nAces > 0 and count + 10 <= 21:
        count += 10 
        usable_ace = 1

    return([count, usable_ace])

def drawCard(n=1):
    return list(random.choice([1,2,3,4,5,6,7,8,9,10,10,10,10],size = n ))

In [355]:
def getEpsGreedyAction(policy, state, epsilon = .1):
    '''
    Get the epsilon greedy action given the state.  
    policy: the policy dictionary
    state: current state.  
    epsilon: parameter for epsilon - greedy alog.  Set to 1 for full greedy.
    '''
    action = None
    if random.rand() <= epsilon:
        action = random.choice(['stick', 'hit'])
    else:
        if state in policy:
            action = policy[state]
        else:
            action = random.choice(['stick', 'hit'])

    return action

def scoreGame(dealer_hand, player_hand):
    ''' 
    score a Game sim.  
    returns -1, 0, 1 when the player loses, draws or wins respectively
    '''
    dealer_count = count(dealer_hand)[0]
    player_count = count(player_hand)[0]

    # player busts
    if player_count > 21:
        return -1

    # dealer busts
    if dealer_count > 21:
        return 1

    # neither busts
    if player_count > dealer_count:
        return 1
    elif player_count < dealer_count:
        return -1
    else:
        return 0

def resetBoard():  
    policy = {} # a dictionary, key:{dealer card, count, usable ace} value:{hist, stick}
    q = {} #The action state value: a dictionary, key:{(dealer card, count, usable ace), action} value:value (G)
    q_n = {} # number of times state action pair was touched. same key as above.  value = n touched

In [ ]:
def playGame(policy, epsilon = .1):
    '''
    Run the MC sim for a single game
    '''
    dealer_hand = drawCard(2) 
    dealer_show = dealer_hand[1]
    player_hand = drawCard(2)
    
    state = tuple([dealer_show] + count(player_hand))
    action = getEpsGreedyAction(policy, state, epsilon)

    episode = [(state, action)]
    while action == 'hit' and state[1] <= 21:
        player_hand += drawCard(1)
        state = tuple([dealer_show] + count(player_hand))
        
        if state[1] > 21:
            break
        action = getEpsGreedyAction(policy, state, epsilon)
        episode.append((state, action))

    # Play dealer
    if state[1] <= 21:
        dealerCount = count(dealer_hand)
        while dealerCount[0] <= 17:
            dealer_hand += drawCard(1)
            dealerCount = count(dealer_hand)

    playerResult = scoreGame(dealer_hand=dealer_hand, player_hand=player_hand)

    res = dict(
        episode = episode,
        dealer_show = dealer_show,
        playerResult = playerResult
    )
    return(res)

In [357]:
def updateBoard(game_result, q, q_n, policy, gamma = 1):
    '''
    Function updates the q value for this state/action pair and state policy (dictionaries)   
    Updates are from the played game as defined by:
    state: final state of the game 
    action: last action of the game that resulted in the state (hit or stick)
    reward: reward (-1, 0, 1) 
    hand: the final hand of the game 
    gamma: discount used to calculate G = gamma*G + R_t+1.
    '''

    episode = game_result['episode']
    dealer_show = game_result["dealer_show"] 
    n_episode = len(episode)

    G = 0
    for i in range(n_episode):
        state = episode[n_episode - i - 1][0]
        action = episode[n_episode - i - 1][1]
        reward = game_result['playerResult'] if i == 0 else 0

        G = gamma * G + reward

        # increment n for this state, action pair
        q_n[(state, action)] = q_n.get((state, action), 0) + 1

        # Update q value for this state action pair
        old_q = q.get((state, action), 0)
        q[(state, action)] = old_q + (G - old_q) / q_n[(state, action)]

        # Update the policy
        hit_val = q.get((state, 'hit'), 0)
        stick_val = q.get((state, 'stick'), 0)
        policy[state] = 'hit' if hit_val >= stick_val else 'stick'

    return(q, q_n, policy)

In [406]:
q_n[(state, action)]

KeyError: ((7, 12, 1), 'stick')

In [404]:
gameResult = playGame(policy={})
gameResult

{'episode': [((7, 13, 0), 'hit'), ((7, 18, 0), 'stick')],
 'dealer_show': 7,
 'playerResult': 1}

In [405]:
updateBoard(gameResult, q, q_n, policy, gamma = 1)

({((10, 19, 0), 'hit'): -0.0003785011355034065,
  ((10, 20, 0), 'hit'): -0.0002702702702702703,
  ((5, 21, 0), 'hit'): -0.0017482517482517483,
  ((5, 11, 0), 'hit'): -0.0042654028436018955,
  ((9, 21, 0), 'hit'): -0.0016806722689075631,
  ((9, 18, 0), 'hit'): -0.001594896331738437,
  ((9, 18, 1), 'hit'): -0.011250000000000001,
  ((7, 17, 0), 'hit'): -0.0014992503748125937,
  ((10, 18, 0), 'hit'): -0.0003642250101173614,
  ((7, 15, 0), 'hit'): -0.0014150943396226416,
  ((6, 14, 0), 'hit'): -0.001601423487544484,
  ((6, 11, 0), 'hit'): -0.004186046511627907,
  ((1, 20, 0), 'hit'): -0.000992282249173098,
  ((4, 18, 0), 'hit'): -0.001466275659824047,
  ((4, 11, 0), 'hit'): -0.0033088235294117647,
  ((6, 16, 0), 'hit'): -0.001490066225165563,
  ((4, 10, 0), 'hit'): -0.0038135593220338985,
  ((4, 16, 0), 'hit'): -0.0015,
  ((4, 21, 1), 'hit'): -0.003474903474903475,
  ((7, 20, 0), 'hit'): -0.001091703056768559,
  ((7, 13, 0), 'hit'): 0.00017064846416382242,
  ((7, 5, 0), 'hit'): -0.013017857142857145,
  ((9, 20, 0), 'hit'): -0.0011904761904761906,
  ((9, 10, 0), 'hit'): -0.004838709677419355,
  ((2, 16, 0), 'hit'): -0.001669449081803005,
  ((2, 6, 0), 'hit'): -0.01173913043478261,
  ((8, 21, 0), 'hit'): -0.0017123287671232876,
  ((8, 12, 0), 'hit'): -0.0019455252918287938,
  ((5, 20, 0), 'hit'): -0.0011350737797956867,
  ((10, 17, 0), 'hit'): -0.0003232242617717478,
  ((9, 16, 0), 'hit'): -0.0017391304347826088,
  ((6, 19, 0), 'hit'): -0.0016129032258064516,
  ((6, 12, 0), 'hit'): -0.0018552875695732839,
  ((6, 9, 0), 'hit'): -0.005192307692307692,
  ((6, 6, 0), 'hit'): -0.010253164556962025,
  ((8, 18, 0), 'hit'): -0.0015408320493066256,
  ((4, 20, 0), 'hit'): -0.0010638297872340426,
  ((4, 17, 1), 'hit'): -0.011538461538461539,
  ((1, 17, 0), 'hit'): -0.001519756838905775,
  ((1, 10, 0), 'hit'): -0.003471428571428572,
  ((1, 18, 0), 'hit'): -0.0014492753623188406,
  ((1, 13, 0), 'hit'): -0.0015625,
  ((7, 14, 0), 'hit'): -0.0017574692442882249,
  ((10, 16, 0), 'hit'): -0.0004152823920265781,
  ((6, 20, 0), 'hit'): -0.0010905125408942203,
  ((6, 15, 0), 'hit'): -0.001669449081803005,
  ((2, 21, 0), 'hit'): -0.0018115942028985507,
  ((2, 17, 0), 'hit'): -0.0014539579967689823,
  ((2, 19, 1), 'hit'): -0.006906315789473686,
  ((10, 21, 0), 'hit'): -0.00042918454935622315,
  ((10, 11, 0), 'hit'): -0.0009404388714733542,
  ((1, 19, 0), 'hit'): -0.0015479876160990713,
  ((1, 11, 0), 'hit'): -0.0036290322580645163,
  ((10, 14, 0), 'hit'): -0.00045578851412944393,
  ((10, 8, 0), 'hit'): -0.0016483516483516484,
  ((4, 14, 0), 'hit'): -0.001949317738791423,
  ((4, 12, 0), 'hit'): -0.0018181818181818182,
  ((7, 19, 0), 'hit'): -0.0014970059880239522,
  ((8, 17, 0), 'hit'): -0.0016835016835016834,
  ((8, 14, 0), 'hit'): -0.0017045454545454547,
  ((8, 11, 0), 'hit'): -0.003417721518987342,
  ((2, 18, 0), 'hit'): -0.0013615733736762482,
  ((2, 21, 1), 'hit'): -0.003515625,
  ((7, 12, 0), 'hit'): -0.0018726591760299626,
  ((5, 18, 0), 'hit'): -0.0013574660633484162,
  ((5, 10, 0), 'hit'): -0.0042452830188679245,
  ((10, 12, 0), 'hit'): -0.0004479840716774515,
  ((10, 21, 1), 'hit'): -0.0008797653958944282,
  ((5, 17, 0), 'hit'): -0.0013615733736762482,
  ((8, 16, 0), 'hit'): -0.0016420361247947454,
  ((2, 14, 0), 'hit'): -0.0016304347826086958,
  ((2, 13, 0), 'hit'): -0.0014136125654450264,
  ((2, 7, 0), 'hit'): -0.007964601769911504,
  ((3, 20, 0), 'hit'): -0.0009879253567508233,
  ((10, 7, 0), 'hit'): -0.0017651331719128333,
  ((10, 13, 0), 'hit'): -0.0004090909090909091,
  ((10, 13, 1), 'hit'): -0.003298642533936652,
  ((1, 19, 1), 'hit'): -0.010112359550561799,
  ((3, 20, 1), 'hit'): -0.008181818181818182,
  ((3, 17, 1), 'hit'): -0.0084375,
  ((2, 14, 1), 'hit'): -0.014210526315789474,
  ((2, 18, 1), 'hit'): -0.01139240506329114,
  ((5, 15, 0), 'hit'): -0.0015358361774744029,
  ((5, 14, 0), 'hit'): -0.001644736842105263,
  ((8, 13, 0), 'hit'): -0.0014889705882352943,
  ((5, 19, 0), 'hit'): -0.00141287284144427,
  ((9, 11, 0), 'hit'): -0.0031395348837209304,
  ((3, 21, 0), 'hit'): -0.0017761989342806395,
  ((3, 11, 0), 'hit'): -0.0038135593220338985,
  ((3, 17, 0), 'hit'): -0.001302250803858521,
  ((3, 12, 0), 'hit'): -0.00186219739292365,
  ((3, 8, 0), 'hit'): -0.005832,
  ((1, 16, 0), 'hit'): -0.0016666666666666668,
  ((1, 8, 0), 'hit'): -0.0057692307692307696,
  ((2, 12, 0), 'hit'): -0.0019157088122605363,
  ((6, 13, 0), 'hit'): -0.0017045454545454547,
  ((4, 15, 0), 'hit'): -0.0017094017094017094,
  ((7, 16, 0), 'hit'): -0.0017667844522968198,
  ((8, 15, 0), 'hit'): -0.0018083182640144665,
  ((5, 13, 0), 'hit'): -0.0016363636363636363,
  ((7, 11, 0), 'hit'): -0.0034090909090909094,
  ((10, 19, 1), 'hit'): -0.00234375,
  ((10, 10, 0), 'hit'): -0.001053864168618267,
  ((10, 15, 0), 'hit'): -0.00044072278536800354,
  ((7, 21, 0), 'hit'): -0.0015923566878980893,
  ((7, 21, 1), 'hit'): -0.0035294117647058825,
  ((10, 9, 0), 'hit'): -0.0013574660633484162,
  ((5, 12, 0), 'hit'): -0.0016423357664233577,
  ((5, 6, 0), 'hit'): -0.009592105263157897,
  ((1, 18, 1), 'hit'): -0.009000000000000001,
  ((1, 13, 1), 'hit'): -0.016875,
  ((9, 14, 0), 'hit'): -0.0018248175182481751,
  ((9, 21, 1), 'hit'): -0.0034090909090909094,
  ((3, 10, 0), 'hit'): -0.00400990099009901,
  ((1, 17, 1), 'hit'): -0.012,
  ((4, 20, 1), 'hit'): -0.006377952755905512,
  ((4, 19, 1), 'hit'): -0.01,
  ((4, 12, 1), 'hit'): -0.027000000000000003,
  ((5, 16, 0), 'hit'): -0.0016835016835016834,
  ((5, 19, 1), 'hit'): -0.006982758620689655,
  ((2, 20, 0), 'hit'): -0.0011049723756906078,
  ((2, 15, 0), 'hit'): -0.0017421602787456446,
  ((2, 5, 0), 'hit'): -0.018367346938775512,
  ((5, 21, 1), 'hit'): -0.0031640625,
  ((8, 4, 0), 'hit'): -0.05,
  ((6, 18, 0), 'hit'): -0.00145985401459854,
  ((6, 10, 0), 'hit'): -0.003970588235294118,
  ((10, 20, 1), 'hit'): -0.002238805970149254,
  ((7, 6, 0), 'hit'): -0.010657894736842106,
  ((9, 13, 0), 'hit'): -0.0017612524461839531,
  ((10, 17, 1), 'hit'): -0.002299684542586751,
  ((9, 19, 0), 'hit'): -0.0015455950540958269,
  ((5, 9, 0), 'hit'): -0.004736842105263158,
  ((5, 15, 1), 'hit'): -0.011842105263157895,
  ((2, 10, 0), 'hit'): -0.0046875,
  ((8, 21, 1), 'hit'): -0.0036290322580645163,
  ((4, 17, 0), 'hit'): -0.0015923566878980893,
  ((4, 13, 0), 'hit'): -0.0016638935108153079,
  ((8, 19, 0), 'hit'): -0.0014577259475218659,
  ((7, 10, 0), 'hit'): -0.003951219512195122,
  ((4, 19, 0), 'hit'): -0.0014705882352941176,
  ((1, 12, 0), 'hit'): -0.0018148820326678765,
  ((1, 9, 0), 'hit'): -0.005084745762711865,
  ((2, 11, 0), 'hit'): -0.003616071428571429,
  ((8, 20, 0), 'hit'): -0.0010895883777239709,
  ((8, 8, 0), 'hit'): -0.006090225563909775,
  ((7, 18, 0), 'hit'): -0.0012857142857142856,
  ((7, 20, 1), 'hit'): -0.009473684210526316,
  ((7, 13, 1), 'hit'): -0.018837209302325582,
  ((3, 15, 0), 'hit'): -0.0017605633802816902,
  ((3, 15, 1), 'hit'): -0.013235294117647059,
  ((4, 8, 0), 'hit'): -0.006279069767441861,
  ((10, 18, 1), 'hit'): -0.002341040462427746,
  ((3, 18, 0), 'hit'): -0.0016474464579901153,
  ((10, 6, 0), 'hit'): -0.0020312693498452015,
  ((1, 21, 1), 'hit'): -0.0036734693877551023,
  ((1, 14, 0), 'hit'): -0.0015126050420168067,
  ((1, 15, 1), 'hit'): -0.011095890410958905,
  ((1, 15, 0), 'hit'): -0.0015734265734265735,
  ((5, 16, 1), 'hit'): -0.0108,
  ((2, 8, 0), 'hit'): -0.00574468085106383,
  ((6, 21, 0), 'hit'): -0.001584786053882726,
  ((6, 21, 1), 'hit'): -0.0033582089552238806,
  ((3, 14, 0), 'hit'): -0.0018587360594795538,
  ((3, 21, 1), 'hit'): -0.0031395348837209304,
  ((6, 17, 0), 'hit'): -0.001584786053882726,
  ((1, 4, 0), 'hit'): -0.031153846153846157,
  ((5, 20, 1), 'hit'): -0.007563025210084034,
  ((5, 14, 1), 'hit'): -0.0140625,
  ((8, 5, 0), 'hit'): -0.01723404255319149,
  ((10, 5, 0), 'hit'): -0.00400990099009901,
  ((5, 18, 1), 'hit'): -0.007673684210526317,
  ((2, 17, 1), 'hit'): -0.011911764705882354,
  ((9, 17, 0), 'hit'): -0.001669449081803005,
  ((4, 5, 0), 'hit'): -0.015789473684210527,
  ((7, 8, 0), 'hit'): -0.004628571428571429,
  ((7, 18, 1), 'hit'): -0.010945945945945947,
  ((7, 15, 1), 'hit'): -0.01338979591836735,
  ((9, 9, 0), 'hit'): -0.004238372093023256,
  ((7, 9, 0), 'hit'): -0.0046875,
  ((8, 18, 1), 'hit'): -0.009642857142857144,
  ((5, 17, 1), 'hit'): -0.012857142857142857,
  ((9, 7, 0), 'hit'): -0.00870967741935484,
  ((9, 4, 0), 'hit'): -0.075,
  ((9, 15, 0), 'hit'): -0.0013989637305699483,
  ((3, 13, 0), 'hit'): -0.0015625,
  ((1, 21, 0), 'hit'): -0.0015625,
  ((9, 12, 0), 'hit'): -0.0016598360655737706,
  ((9, 15, 1), 'hit'): -0.015254237288135594,
  ((9, 12, 1), 'hit'): -0.032400000000000005,
  ((9, 20, 1), 'hit'): -0.007641509433962265,
  ((3, 16, 0), 'hit'): -0.0014106583072100315,
  ((8, 9, 0), 'hit'): -0.004189655172413794,
  ((7, 19, 1), 'hit'): -0.008181818181818182,
  ((7, 17, 1), 'hit'): -0.010384615384615384,
  ((5, 8, 0), 'hit'): -0.007758620689655172,
  ((3, 14, 1), 'hit'): -0.008303765625000003,
  ((4, 21, 0), 'hit'): -0.0017241379310344827,
  ((4, 9, 0), 'hit'): -0.005487804878048781,
  ((4, 7, 0), 'hit'): -0.006688073394495414,
  ((6, 5, 0), 'hit'): -0.012857142857142859,
  ((6, 8, 0), 'hit'): -0.005481203007518798,
  ((8, 10, 0), 'hit'): -0.005056179775280899,
  ((8, 19, 1), 'hit'): -0.00967741935483871,
  ((10, 14, 1), 'hit'): -0.0033196721311475413,
  ((3, 9, 0), 'hit'): -0.004918032786885246,
  ((6, 16, 1), 'hit'): -0.01265625,
  ((9, 8, 0), 'hit'): -0.0072,
  ((8, 20, 1), 'hit'): -0.009574468085106383,
  ((7, 14, 1), 'hit'): -0.013278688524590165,
  ((10, 16, 1), 'hit'): -0.0033210332103321034,
  ((3, 19, 0), 'hit'): -0.0015625,
  ((9, 6, 0), 'hit'): -0.010843373493975903,
  ((3, 12, 1), 'hit'): -0.035217391304347825,
  ((2, 19, 0), 'hit'): -0.001488095238095238,
  ((2, 13, 1), 'hit'): -0.014516129032258065,
  ((3, 7, 0), 'hit'): -0.007105263157894737,
  ((2, 9, 0), 'hit'): -0.005421686746987952,
  ((7, 7, 0), 'hit'): -0.006806722689075631,
  ((10, 12, 1), 'hit'): -0.006496039603960398,
  ((4, 15, 1), 'hit'): -0.011095890410958905,
  ((3, 16, 1), 'hit'): -0.014754098360655738,
  ((4, 13, 1), 'hit'): -0.011758064516129034,
  ((6, 7, 0), 'hit'): -0.007941176470588236,
  ((9, 16, 1), 'hit'): -0.014516129032258065,
  ((9, 5, 0), 'hit'): -0.013728813559322034,
  ((4, 14, 1), 'hit'): -0.01840909090909091,
  ((7, 16, 1), 'hit'): -0.016875,
  ((6, 15, 1), 'hit'): -0.010720588235294119,
  ((10, 15, 1), 'hit'): -0.0036,
  ((5, 4, 0), 'hit'): -0.035217391304347825,
  ((1, 5, 0), 'hit'): -0.01956521739130435,
  ((8, 17, 1), 'hit'): -0.010384615384615384,
  ((8, 15, 1), 'hit'): -0.015000000000000001,
  ((3, 6, 0), 'hit'): -0.00745568181818182,
  ((2, 20, 1), 'hit'): -0.00967741935483871,
  ((2, 15, 1), 'hit'): -0.012150000000000001,
  ((1, 6, 0), 'hit'): -0.010582258064516131,
  ((6, 13, 1), 'hit'): -0.021891891891891894,
  ((1, 7, 0), 'hit'): -0.008333333333333333,
  ((3, 5, 0), 'hit'): -0.014210526315789474,
  ((8, 6, 0), 'hit'): -0.010384615384615384,
  ((8, 16, 1), 'hit'): -0.014464285714285716,
  ((8, 13, 1), 'hit'): -0.021951219512195124,
  ((3, 19, 1), 'hit'): -0.010112359550561799,
  ((3, 13, 1), 'hit'): -0.013064516129032259,
  ((1, 14, 1), 'hit'): -0.016875,
  ((5, 13, 1), 'hit'): -0.010880597014925374,
  ((5, 7, 0), 'hit'): -0.006394736842105264,
  ((2, 16, 1), 'hit'): -0.007873200000000002,
  ((6, 4, 0), 'hit'): -0.0405,
  ((1, 16, 1), 'hit'): -0.011842105263157895,
  ((2, 12, 1), 'hit'): -0.030000000000000002,
  ((1, 12, 1), 'hit'): -0.024324324324324326,
  ((10, 4, 0), 'hit'): -0.008571428571428572,
  ((9, 19, 1), 'hit'): -0.010588235294117647,
  ((4, 16, 1), 'hit'): -0.011215384615384617,
  ((6, 20, 1), 'hit'): -0.007758620689655172,
  ((6, 12, 1), 'hit'): -0.03280500000000001,
  ((7, 4, 0), 'hit'): -0.028125,
  ((8, 14, 1), 'hit'): -0.011911764705882354,
  ((9, 13, 1), 'hit'): -0.009162775862068968,
  ((4, 18, 1), 'hit'): -0.009101123595505618,
  ((4, 6, 0), 'hit'): -0.010125,
  ((1, 20, 1), 'hit'): -0.00909090909090909,
  ((6, 19, 1), 'hit'): -0.010588235294117647,
  ((6, 14, 1), 'hit'): -0.014464285714285716,
  ((9, 17, 1), 'hit'): -0.008813283582089555,
  ((6, 18, 1), 'hit'): -0.01139240506329114,
  ((8, 7, 0), 'hit'): -0.006508928571428573,
  ((5, 5, 0), 'hit'): -0.012568965517241381,
  ((2, 4, 0), 'hit'): -0.03214285714285715,
  ((3, 18, 1), 'hit'): -0.01,
  ((6, 17, 1), 'hit'): -0.010253164556962025,
  ((3, 4, 0), 'hit'): -0.0391304347826087,
  ((5, 12, 1), 'hit'): -0.03333333333333333,
  ((9, 14, 1), 'hit'): -0.02131578947368421,
  ((4, 4, 0), 'hit'): -0.018452812500000006,
  ((8, 12, 1), 'hit'): -0.02982272727272728,
  ((7, 12, 1), 'hit'): -0.03375,
  ((7, 18, 0), 'stick'): 1.0},
 {((10, 19, 0), 'hit'): 2642,
  ((10, 20, 0), 'hit'): 3700,
  ((5, 21, 0), 'hit'): 572,
  ((5, 11, 0), 'hit'): 211,
  ((9, 21, 0), 'hit'): 595,
  ((9, 18, 0), 'hit'): 627,
  ((9, 18, 1), 'hit'): 72,
  ((7, 17, 0), 'hit'): 667,
  ((10, 18, 0), 'hit'): 2471,
  ((7, 15, 0), 'hit'): 636,
  ((6, 14, 0), 'hit'): 562,
  ((6, 11, 0), 'hit'): 215,
  ((1, 20, 0), 'hit'): 907,
  ((4, 18, 0), 'hit'): 682,
  ((4, 11, 0), 'hit'): 272,
  ((6, 16, 0), 'hit'): 604,
  ((4, 10, 0), 'hit'): 236,
  ((4, 16, 0), 'hit'): 600,
  ((4, 21, 1), 'hit'): 259,
  ((7, 20, 0), 'hit'): 916,
  ((7, 13, 0), 'hit'): 586,
  ((7, 5, 0), 'hit'): 56,
  ((9, 20, 0), 'hit'): 840,
  ((9, 10, 0), 'hit'): 186,
  ((2, 16, 0), 'hit'): 599,
  ((2, 6, 0), 'hit'): 69,
  ((8, 21, 0), 'hit'): 584,
  ((8, 12, 0), 'hit'): 514,
  ((5, 20, 0), 'hit'): 881,
  ((10, 17, 0), 'hit'): 2506,
  ((9, 16, 0), 'hit'): 575,
  ((6, 19, 0), 'hit'): 620,
  ((6, 12, 0), 'hit'): 539,
  ((6, 9, 0), 'hit'): 156,
  ((6, 6, 0), 'hit'): 79,
  ((8, 18, 0), 'hit'): 649,
  ((4, 20, 0), 'hit'): 940,
  ((4, 17, 1), 'hit'): 78,
  ((1, 17, 0), 'hit'): 658,
  ((1, 10, 0), 'hit'): 210,
  ((1, 18, 0), 'hit'): 690,
  ((1, 13, 0), 'hit'): 576,
  ((7, 14, 0), 'hit'): 569,
  ((10, 16, 0), 'hit'): 2408,
  ((6, 20, 0), 'hit'): 917,
  ((6, 15, 0), 'hit'): 599,
  ((2, 21, 0), 'hit'): 552,
  ((2, 17, 0), 'hit'): 619,
  ((2, 19, 1), 'hit'): 95,
  ((10, 21, 0), 'hit'): 2330,
  ((10, 11, 0), 'hit'): 957,
  ((1, 19, 0), 'hit'): 646,
  ((1, 11, 0), 'hit'): 248,
  ((10, 14, 0), 'hit'): 2194,
  ((10, 8, 0), 'hit'): 546,
  ((4, 14, 0), 'hit'): 513,
  ((4, 12, 0), 'hit'): 550,
  ((7, 19, 0), 'hit'): 668,
  ((8, 17, 0), 'hit'): 594,
  ((8, 14, 0), 'hit'): 528,
  ((8, 11, 0), 'hit'): 237,
  ((2, 18, 0), 'hit'): 661,
  ((2, 21, 1), 'hit'): 256,
  ((7, 12, 0), 'hit'): 534,
  ((5, 18, 0), 'hit'): 663,
  ((5, 10, 0), 'hit'): 212,
  ((10, 12, 0), 'hit'): 2009,
  ((10, 21, 1), 'hit'): 1023,
  ((5, 17, 0), 'hit'): 661,
  ((8, 16, 0), 'hit'): 609,
  ((2, 14, 0), 'hit'): 552,
  ((2, 13, 0), 'hit'): 573,
  ((2, 7, 0), 'hit'): 113,
  ((3, 20, 0), 'hit'): 911,
  ((10, 7, 0), 'hit'): 413,
  ((10, 13, 0), 'hit'): 2200,
  ((10, 13, 1), 'hit'): 221,
  ((1, 19, 1), 'hit'): 89,
  ((3, 20, 1), 'hit'): 99,
  ((3, 17, 1), 'hit'): 96,
  ((2, 14, 1), 'hit'): 57,
  ((2, 18, 1), 'hit'): 79,
  ((5, 15, 0), 'hit'): 586,
  ((5, 14, 0), 'hit'): 608,
  ((8, 13, 0), 'hit'): 544,
  ((5, 19, 0), 'hit'): 637,
  ((9, 11, 0), 'hit'): 258,
  ((3, 21, 0), 'hit'): 563,
  ((3, 11, 0), 'hit'): 236,
  ((3, 17, 0), 'hit'): 622,
  ((3, 12, 0), 'hit'): 537,
  ((3, 8, 0), 'hit'): 125,
  ((1, 16, 0), 'hit'): 600,
  ((1, 8, 0), 'hit'): 156,
  ((2, 12, 0), 'hit'): 522,
  ((6, 13, 0), 'hit'): 528,
  ((4, 15, 0), 'hit'): 585,
  ((7, 16, 0), 'hit'): 566,
  ((8, 15, 0), 'hit'): 553,
  ((5, 13, 0), 'hit'): 550,
  ((7, 11, 0), 'hit'): 264,
  ((10, 19, 1), 'hit'): 384,
  ((10, 10, 0), 'hit'): 854,
  ((10, 15, 0), 'hit'): 2269,
  ((7, 21, 0), 'hit'): 628,
  ((7, 21, 1), 'hit'): 255,
  ((10, 9, 0), 'hit'): 663,
  ((5, 12, 0), 'hit'): 548,
  ((5, 6, 0), 'hit'): 76,
  ((1, 18, 1), 'hit'): 81,
  ((1, 13, 1), 'hit'): 48,
  ((9, 14, 0), 'hit'): 548,
  ((9, 21, 1), 'hit'): 264,
  ((3, 10, 0), 'hit'): 202,
  ((1, 17, 1), 'hit'): 75,
  ((4, 20, 1), 'hit'): 127,
  ((4, 19, 1), 'hit'): 90,
  ((4, 12, 1), 'hit'): 27,
  ((5, 16, 0), 'hit'): 594,
  ((5, 19, 1), 'hit'): 116,
  ((2, 20, 0), 'hit'): 905,
  ((2, 15, 0), 'hit'): 574,
  ((2, 5, 0), 'hit'): 49,
  ((5, 21, 1), 'hit'): 256,
  ((8, 4, 0), 'hit'): 18,
  ((6, 18, 0), 'hit'): 685,
  ((6, 10, 0), 'hit'): 204,
  ((10, 20, 1), 'hit'): 402,
  ((7, 6, 0), 'hit'): 76,
  ((9, 13, 0), 'hit'): 511,
  ((10, 17, 1), 'hit'): 317,
  ((9, 19, 0), 'hit'): 647,
  ((5, 9, 0), 'hit'): 171,
  ((5, 15, 1), 'hit'): 76,
  ((2, 10, 0), 'hit'): 192,
  ((8, 21, 1), 'hit'): 248,
  ((4, 17, 0), 'hit'): 628,
  ((4, 13, 0), 'hit'): 601,
  ((8, 19, 0), 'hit'): 686,
  ((7, 10, 0), 'hit'): 205,
  ((4, 19, 0), 'hit'): 680,
  ((1, 12, 0), 'hit'): 551,
  ((1, 9, 0), 'hit'): 177,
  ((2, 11, 0), 'hit'): 224,
  ((8, 20, 0), 'hit'): 826,
  ((8, 8, 0), 'hit'): 133,
  ((7, 18, 0), 'hit'): 700,
  ((7, 20, 1), 'hit'): 95,
  ((7, 13, 1), 'hit'): 43,
  ((3, 15, 0), 'hit'): 568,
  ((3, 15, 1), 'hit'): 68,
  ((4, 8, 0), 'hit'): 129,
  ((10, 18, 1), 'hit'): 346,
  ((3, 18, 0), 'hit'): 607,
  ((10, 6, 0), 'hit'): 323,
  ((1, 21, 1), 'hit'): 245,
  ((1, 14, 0), 'hit'): 595,
  ((1, 15, 1), 'hit'): 73,
  ((1, 15, 0), 'hit'): 572,
  ((5, 16, 1), 'hit'): 75,
  ((2, 8, 0), 'hit'): 141,
  ((6, 21, 0), 'hit'): 631,
  ((6, 21, 1), 'hit'): 268,
  ((3, 14, 0), 'hit'): 538,
  ((3, 21, 1), 'hit'): 258,
  ((6, 17, 0), 'hit'): 631,
  ((1, 4, 0), 'hit'): 26,
  ((5, 20, 1), 'hit'): 119,
  ((5, 14, 1), 'hit'): 64,
  ((8, 5, 0), 'hit'): 47,
  ((10, 5, 0), 'hit'): 202,
  ((5, 18, 1), 'hit'): 95,
  ((2, 17, 1), 'hit'): 68,
  ((9, 17, 0), 'hit'): 599,
  ((4, 5, 0), 'hit'): 57,
  ((7, 8, 0), 'hit'): 175,
  ((7, 18, 1), 'hit'): 74,
  ((7, 15, 1), 'hit'): 49,
  ((9, 9, 0), 'hit'): 172,
  ((7, 9, 0), 'hit'): 192,
  ((8, 18, 1), 'hit'): 84,
  ((5, 17, 1), 'hit'): 70,
  ((9, 7, 0), 'hit'): 93,
  ((9, 4, 0), 'hit'): 12,
  ((9, 15, 0), 'hit'): 579,
  ((3, 13, 0), 'hit'): 576,
  ((1, 21, 0), 'hit'): 640,
  ((9, 12, 0), 'hit'): 488,
  ((9, 15, 1), 'hit'): 59,
  ((9, 12, 1), 'hit'): 25,
  ((9, 20, 1), 'hit'): 106,
  ((3, 16, 0), 'hit'): 638,
  ((8, 9, 0), 'hit'): 174,
  ((7, 19, 1), 'hit'): 110,
  ((7, 17, 1), 'hit'): 78,
  ((5, 8, 0), 'hit'): 116,
  ((3, 14, 1), 'hit'): 64,
  ((4, 21, 0), 'hit'): 580,
  ((4, 9, 0), 'hit'): 164,
  ((4, 7, 0), 'hit'): 109,
  ((6, 5, 0), 'hit'): 63,
  ((6, 8, 0), 'hit'): 133,
  ((8, 10, 0), 'hit'): 178,
  ((8, 19, 1), 'hit'): 93,
  ((10, 14, 1), 'hit'): 244,
  ((3, 9, 0), 'hit'): 183,
  ((6, 16, 1), 'hit'): 64,
  ((9, 8, 0), 'hit'): 125,
  ((8, 20, 1), 'hit'): 94,
  ((7, 14, 1), 'hit'): 61,
  ((10, 16, 1), 'hit'): 271,
  ((3, 19, 0), 'hit'): 640,
  ((9, 6, 0), 'hit'): 83,
  ((3, 12, 1), 'hit'): 23,
  ((2, 19, 0), 'hit'): 672,
  ((2, 13, 1), 'hit'): 62,
  ((3, 7, 0), 'hit'): 114,
  ((2, 9, 0), 'hit'): 166,
  ((7, 7, 0), 'hit'): 119,
  ((10, 12, 1), 'hit'): 101,
  ((4, 15, 1), 'hit'): 73,
  ((3, 16, 1), 'hit'): 61,
  ((4, 13, 1), 'hit'): 62,
  ((6, 7, 0), 'hit'): 102,
  ((9, 16, 1), 'hit'): 62,
  ((9, 5, 0), 'hit'): 59,
  ((4, 14, 1), 'hit'): 44,
  ((7, 16, 1), 'hit'): 48,
  ((6, 15, 1), 'hit'): 68,
  ((10, 15, 1), 'hit'): 250,
  ((5, 4, 0), 'hit'): 23,
  ((1, 5, 0), 'hit'): 46,
  ((8, 17, 1), 'hit'): 78,
  ((8, 15, 1), 'hit'): 54,
  ((3, 6, 0), 'hit'): 88,
  ((2, 20, 1), 'hit'): 93,
  ((2, 15, 1), 'hit'): 60,
  ((1, 6, 0), 'hit'): 62,
  ((6, 13, 1), 'hit'): 37,
  ((1, 7, 0), 'hit'): 108,
  ((3, 5, 0), 'hit'): 57,
  ((8, 6, 0), 'hit'): 78,
  ((8, 16, 1), 'hit'): 56,
  ((8, 13, 1), 'hit'): 41,
  ((3, 19, 1), 'hit'): 89,
  ((3, 13, 1), 'hit'): 62,
  ((1, 14, 1), 'hit'): 48,
  ((5, 13, 1), 'hit'): 67,
  ((5, 7, 0), 'hit'): 114,
  ((2, 16, 1), 'hit'): 75,
  ((6, 4, 0), 'hit'): 20,
  ((1, 16, 1), 'hit'): 76,
  ((2, 12, 1), 'hit'): 27,
  ((1, 12, 1), 'hit'): 37,
  ((10, 4, 0), 'hit'): 105,
  ((9, 19, 1), 'hit'): 85,
  ((4, 16, 1), 'hit'): 65,
  ((6, 20, 1), 'hit'): 116,
  ((6, 12, 1), 'hit'): 18,
  ((7, 4, 0), 'hit'): 32,
  ((8, 14, 1), 'hit'): 68,
  ((9, 13, 1), 'hit'): 58,
  ((4, 18, 1), 'hit'): 89,
  ((4, 6, 0), 'hit'): 80,
  ((1, 20, 1), 'hit'): 99,
  ((6, 19, 1), 'hit'): 85,
  ((6, 14, 1), 'hit'): 56,
  ((9, 17, 1), 'hit'): 67,

In [358]:
def runSim(policy = {}, q = {}, q_n = {}, gamma = .9, epsilon = .1, n_cycles = 1_100_000):
    '''
    Run the simulation.  If I save policy, q and q_n I can pass them in and continue the simulation.
    '''
    for _ in range(n_cycles):
        gameResult = playGame(policy, epsilon)   
        updateBoard(gameResult, q, q_n, policy, gamma)

    res = dict(
        policy = policy,
        q = q,
        q_n = q_n
    )
    return(res)

In [378]:
x = runSim()

In [ ]:
q = x['q']
policy = x['policy']

In [381]:
import pandas as pd

rows = []

for (state, action), value in q.items():
    dealer, player_sum, usable_ace = state
    rows.append({
        'dealer': dealer,
        'player_sum': player_sum,
        'usable_ace': usable_ace,
        'action': action,
        'q_value': value
    })

df = pd.DataFrame(rows)

In [392]:
import pandas as pd

rows = []

for state, action in policy.items():
    dealer, player_sum, usable_ace = state
    rows.append({
        'dealer': dealer,
        'player_sum': player_sum,
        'usable_ace': usable_ace,
        'action': action
    })

df_policy = pd.DataFrame(rows)

In [395]:
df_policy.query('player_sum == 21')

     dealer  player_sum  usable_ace action
2         5          21           0  stick
4         9          21           0  stick
18        4          21           1  stick
26        8          21           0  stick
46        2          21           0  stick
49       10          21           0  stick
62        2          21           1  stick
67       10          21           1  stick
87        3          21           0  stick
104       7          21           0  stick
105       7          21           1  stick
112       9          21           1  stick
123       5          21           1  stick
135       8          21           1  stick
155       1          21           1  stick
161       6          21           0  stick
162       6          21           1  stick
164       3          21           1  stick
186       1          21           0  stick
197       4          21           0  stick

In [396]:
df_policy.value_counts('action')

action
stick    280
Name: count, dtype: int64

In [401]:
df.action.value_counts()

action
hit    280
Name: count, dtype: int64

In [385]:
df.query('player_sum == 21').sort_values('q_value')

     dealer  player_sum  usable_ace action   q_value
155       1          21           1    hit -0.003673
135       8          21           1    hit -0.003629
105       7          21           1    hit -0.003529
62        2          21           1    hit -0.003516
18        4          21           1    hit -0.003475
112       9          21           1    hit -0.003409
162       6          21           1    hit -0.003358
123       5          21           1    hit -0.003164
164       3          21           1    hit -0.003140
46        2          21           0    hit -0.001812
87        3          21           0    hit -0.001776
2         5          21           0    hit -0.001748
197       4          21           0    hit -0.001724
26        8          21           0    hit -0.001712
4         9          21           0    hit -0.001681
104       7          21           0    hit -0.001592
161       6          21           0    hit -0.001585
186       1          21           0    hit -0.001563
67       10          21           1    hit -0.000880
49       10          21           0    hit -0.000429

In [371]:
for k, v in q.items():
    if k[1] == 'stick':
        print(k,v)

In [362]:
sorted_q = sorted(
    q.items(),
    key=lambda x: (x[0][0][1], x[0][0][2])
)

sorted_q

[(((8, 4, 0), 'hit'), -0.05),
 (((1, 4, 0), 'hit'), -0.031153846153846157),
 (((9, 4, 0), 'hit'), -0.075),
 (((5, 4, 0), 'hit'), -0.035217391304347825),
 (((6, 4, 0), 'hit'), -0.0405),
 (((10, 4, 0), 'hit'), -0.008571428571428572),
 (((7, 4, 0), 'hit'), -0.028125),
 (((2, 4, 0), 'hit'), -0.03214285714285715),
 (((3, 4, 0), 'hit'), -0.0391304347826087),
 (((4, 4, 0), 'hit'), -0.018452812500000006),
 (((7, 5, 0), 'hit'), -0.013017857142857145),
 (((2, 5, 0), 'hit'), -0.018367346938775512),
 (((8, 5, 0), 'hit'), -0.01723404255319149),
 (((10, 5, 0), 'hit'), -0.00400990099009901),
 (((4, 5, 0), 'hit'), -0.015789473684210527),
 (((6, 5, 0), 'hit'), -0.012857142857142859),
 (((9, 5, 0), 'hit'), -0.013728813559322034),
 (((1, 5, 0), 'hit'), -0.01956521739130435),
 (((3, 5, 0), 'hit'), -0.014210526315789474),
 (((5, 5, 0), 'hit'), -0.012568965517241381),
 (((2, 6, 0), 'hit'), -0.01173913043478261),
 (((6, 6, 0), 'hit'), -0.010253164556962025),
 (((5, 6, 0), 'hit'), -0.009592105263157897),
 (((7, 6, 0), 'hit'), -0.010657894736842106),
 (((10, 6, 0), 'hit'), -0.0020312693498452015),
 (((9, 6, 0), 'hit'), -0.010843373493975903),
 (((3, 6, 0), 'hit'), -0.00745568181818182),
 (((1, 6, 0), 'hit'), -0.010582258064516131),
 (((8, 6, 0), 'hit'), -0.010384615384615384),
 (((4, 6, 0), 'hit'), -0.010125),
 (((2, 7, 0), 'hit'), -0.007964601769911504),
 (((10, 7, 0), 'hit'), -0.0017651331719128333),
 (((9, 7, 0), 'hit'), -0.00870967741935484),
 (((4, 7, 0), 'hit'), -0.006688073394495414),
 (((3, 7, 0), 'hit'), -0.007105263157894737),
 (((7, 7, 0), 'hit'), -0.006806722689075631),
 (((6, 7, 0), 'hit'), -0.007941176470588236),
 (((1, 7, 0), 'hit'), -0.008333333333333333),
 (((5, 7, 0), 'hit'), -0.006394736842105264),
 (((8, 7, 0), 'hit'), -0.006508928571428573),
 (((10, 8, 0), 'hit'), -0.0016483516483516484),
 (((3, 8, 0), 'hit'), -0.005832),
 (((1, 8, 0), 'hit'), -0.0057692307692307696),
 (((8, 8, 0), 'hit'), -0.006090225563909775),
 (((4, 8, 0), 'hit'), -0.006279069767441861),
 (((2, 8, 0), 'hit'), -0.00574468085106383),
 (((7, 8, 0), 'hit'), -0.004628571428571429),
 (((5, 8, 0), 'hit'), -0.007758620689655172),
 (((6, 8, 0), 'hit'), -0.005481203007518798),
 (((9, 8, 0), 'hit'), -0.0072),
 (((6, 9, 0), 'hit'), -0.005192307692307692),
 (((10, 9, 0), 'hit'), -0.0013574660633484162),
 (((5, 9, 0), 'hit'), -0.004736842105263158),
 (((1, 9, 0), 'hit'), -0.005084745762711865),
 (((9, 9, 0), 'hit'), -0.004238372093023256),
 (((7, 9, 0), 'hit'), -0.0046875),
 (((8, 9, 0), 'hit'), -0.004189655172413794),
 (((4, 9, 0), 'hit'), -0.005487804878048781),
 (((3, 9, 0), 'hit'), -0.004918032786885246),
 (((2, 9, 0), 'hit'), -0.005421686746987952),
 (((4, 10, 0), 'hit'), -0.0038135593220338985),
 (((9, 10, 0), 'hit'), -0.004838709677419355),
 (((1, 10, 0), 'hit'), -0.003471428571428572),
 (((5, 10, 0), 'hit'), -0.0042452830188679245),
 (((10, 10, 0), 'hit'), -0.001053864168618267),
 (((3, 10, 0), 'hit'), -0.00400990099009901),
 (((6, 10, 0), 'hit'), -0.003970588235294118),
 (((2, 10, 0), 'hit'), -0.0046875),
 (((7, 10, 0), 'hit'), -0.003951219512195122),
 (((8, 10, 0), 'hit'), -0.005056179775280899),
 (((5, 11, 0), 'hit'), -0.0042654028436018955),
 (((6, 11, 0), 'hit'), -0.004186046511627907),
 (((4, 11, 0), 'hit'), -0.0033088235294117647),
 (((10, 11, 0), 'hit'), -0.0009404388714733542),
 (((1, 11, 0), 'hit'), -0.0036290322580645163),
 (((8, 11, 0), 'hit'), -0.003417721518987342),
 (((9, 11, 0), 'hit'), -0.0031395348837209304),
 (((3, 11, 0), 'hit'), -0.0038135593220338985),
 (((7, 11, 0), 'hit'), -0.0034090909090909094),
 (((2, 11, 0), 'hit'), -0.003616071428571429),
 (((8, 12, 0), 'hit'), -0.0019455252918287938),
 (((6, 12, 0), 'hit'), -0.0018552875695732839),
 (((4, 12, 0), 'hit'), -0.0018181818181818182),
 (((7, 12, 0), 'hit'), -0.0018726591760299626),
 (((10, 12, 0), 'hit'), -0.0004479840716774515),
 (((3, 12, 0), 'hit'), -0.00186219739292365),
 (((2, 12, 0), 'hit'), -0.0019157088122605363),
 (((5, 12, 0), 'hit'), -0.0016423357664233577),
 (((1, 12, 0), 'hit'), -0.0018148820326678765),
 (((9, 12, 0), 'hit'), -0.0016598360655737706),
 (((4, 12, 1), 'hit'), -0.027000000000000003),
 (((9, 12, 1), 'hit'), -0.032400000000000005),
 (((3, 12, 1), 'hit'), -0.035217391304347825),
 (((10, 12, 1), 'hit'), -0.006496039603960398),
 (((2, 12, 1), 'hit'), -0.030000000000000002),
 (((1, 12, 1), 'hit'), -0.024324324324324326),
 (((6, 12, 1), 'hit'), -0.03280500000000001),
 (((5, 12, 1), 'hit'), -0.03333333333333333),
 (((8, 12, 1), 'hit'), -0.02982272727272728),
 (((7, 12, 1), 'hit'), -0.03375),
 (((7, 13, 0), 'hit'), -0.0015384615384615385),
 (((1, 13, 0), 'hit'), -0.0015625),
 (((2, 13, 0), 'hit'), -0.0014136125654450264),
 (((10, 13, 0), 'hit'), -0.0004090909090909091),
 (((8, 13, 0), 'hit'), -0.0014889705882352943),
 (((6, 13, 0), 'hit'), -0.0017045454545454547),
 (((5, 13, 0), 'hit'), -0.0016363636363636363),
 (((9, 13, 0), 'hit'), -0.0017612524461839531),
 (((4, 13, 0), 'hit'), -0.0016638935108153079),
 (((3, 13, 0), 'hit'), -0.0015625),
 (((10, 13, 1), 'hit'), -0.003298642533936652),
 (((1, 13, 1), 'hit'), -0.016875),
 (((7, 13, 1), 'hit'), -0.018837209302325582),
 (((2, 13, 1), 'hit'), -0.014516129032258065),
 (((4, 13, 1), 'hit'), -0.011758064516129034),
 (((6, 13, 1), 'hit'), -0.021891891891891894),
 (((8, 13, 1), 'hit'), -0.021951219512195124),
 (((3, 13, 1), 'hit'), -0.013064516129032259),
 (((5, 13, 1), 'hit'), -0.010880597014925374),
 (((9, 13, 1), 'hit'), -0.009162775862068968),
 (((6, 14, 0), 'hit'), -0.001601423487544484),
 (((7, 14, 0), 'hit'), -0.0017574692442882249),
 (((10, 14, 0), 'hit'), -0.00045578851412944393),
 (((4, 14, 0), 'hit'), -0.001949317738791423),
 (((8, 14, 0), 'hit'), -0.0017045454545454547),
 (((2, 14, 0), 'hit'), -0.0016304347826086958),
 (((5, 14, 0), 'hit'), -0.001644736842105263),
 (((9, 14, 0), 'hit'), -0.0018248175182481751),
 (((1, 14, 0), 'hit'), -0.0015126050420168067),
 (((3, 14, 0), 'hit'), -0.0018587360594795538),
 (((2, 14, 1), 'hit'), -0.014210526315789474),
 (((5, 14, 1), 'hit'), -0.0140625),
 (((3, 14, 1), 'hit'), -0.008303765625000003),
 (((10, 14, 1), 'hit'), -0.0033196721311475413),
 (((7, 14, 1), 'hit'), -0.013278688524590165),
 (((4, 14, 1), 'hit'), -0.01840909090909091),
 (((1, 14, 1), 'hit'), -0.016875),
 (((8, 14, 1), 'hit'), -0.011911764705882354),
 (((6, 14, 1), 'hit'), -0.014464285714285716),
 (((9, 14, 1), 'hit'), -0.02131578947368421),
 (((7, 15, 0), 'hit'), -0.0014150943396226416),
 (((6, 15, 0), 'hit'), -0.001669449081803005),
 (((5, 15, 0), 'hit'), -0.0015358361774744029),
 (((4, 15, 0), 'hit'), -0.0017094017094017094),
 (((8, 15, 0), 'hit'), -0.0018083182640144665),
 (((10, 15, 0), 'hit'), -0.00044072278536800354),
 (((2, 15, 0), 'hit'), -0.0017421602787456446),
 (((3, 15, 0), 'hit'), -0.0017605633802816902),
 (((1, 15, 0), 'hit'), -0.0015734265734265735),
 (((9, 15, 0), 'hit'), -0.0013989637305699483),
 (((5, 15, 1), 'hit'), -0.011842105263157895),
 (((3, 15, 1), 'hit'), -0.013235294117647059),
 (((1, 15, 1), 'hit'), -0.011095890410958905),
 (((7, 15, 1), 'hit'), -0.01338979591836735),
 (((9, 15, 1), 'hit'), -0.015254237288135594),
 (((4, 15, 1), 'hit'), -0.011095890410958905),
 (((6, 15, 1), 'hit'), -0.010720588235294119),
 (((10, 15, 1), 'hit'), -0.0036),
 (((8, 15, 1), 'hit'), -0.015000000000000001),
 (((2, 15, 1), 'hit'), -0.012150000000000001),
 (((6, 16, 0), 'hit'), -0.001490066225165563),
 (((4, 16, 0), 'hit'), -0.0015),
 (((2, 16, 0), 'hit'), -0.001669449081803005),
 (((9, 16, 0), 'hit'), -0.0017391304347826088),
 (((10, 16, 0), 'hit'), -0.0004152823920265781),
 (((8, 16, 0), 'hit'), -0.0016420361247947454),
 (((1, 16, 0), 'hit'), -0.0016666666666666668),
 (((7, 16, 0), 'hit'), -0.0017667844522968198),
 (((5, 16, 0), 'hit'), -0.0016835016835016834),
 (((3, 16, 0), 'hit'), -0.0014106583072100315),
 (((5, 16, 1), 'hit'), -0.0108),
 (((6, 16, 1), 'hit'), -0.01265625),
 (((10, 16, 1), 'hit'), -0.0033210332103321034),
 (((3, 16, 1), 'hit'), -0.014754098360655738),
 (((9, 16, 1), 'hit'), -0.014516129032258065),
 (((7, 16, 1), 'hit'), -0.016875),
 (((8, 16, 1), 'hit'), -0.014464285714285716),
 (((2, 16, 1), 'hit'), -0.007873200000000002),
 (((1, 16, 1), 'hit'), -0.011842105263157895),
 (((4, 16, 1), 'hit'), -0.011215384615384617),
 (((7, 17, 0), 'hit'), -0.0014992503748125937),
 (((10, 17, 0), 'hit'), -0.0003232242617717478),
 (((1, 17, 0), 'hit'), -0.001519756838905775),
 (((2, 17, 0), 'hit'), -0.0014539579967689823),
 (((8, 17, 0), 'hit'), -0.0016835016835016834),
 (((5, 17, 0), 'hit'), -0.0013615733736762482),
 (((3, 17, 0), 'hit'), -0.001302250803858521),
 (((4, 17, 0), 'hit'), -0.0015923566878980893),
 (((6, 17, 0), 'hit'), -0.001584786053882726),
 (((9, 17, 0), 'hit'), -0.001669449081803005),
 (((4, 17, 1), 'hit'), -0.011538461538461539),
 (((3, 17, 1), 'hit'), -0.0084375),
 (((1, 17, 1), 'hit'), -0.012),
 (((10, 17, 1), 'hit'), -0.002299684542586751),
 (((2, 17, 1), 'hit'), -0.011911764705882354),
 (((5, 17, 1), 'hit'), -0.012857142857142857),
 (((7, 17, 1), 'hit'), -0.010384615384615384),
 (((8, 17, 1), 'hit'), -0.010384615384615384),
 (((9, 17, 1), 'hit'), -0.008813283582089555),
 (((6, 17, 1), 'hit'), -0.010253164556962025),
 (((9, 18, 0), 'hit'), -0.001594896331738437),
 (((10, 18, 0), 'hit'), -0.0003642250101173614),
 (((4, 18, 0), 'hit'), -0.001466275659824047),
 (((8, 18, 0), 'hit'), -0.0015408320493066256),
 (((1, 18, 0), 'hit'), -0.0014492753623188406),
 (((2, 18, 0), 'hit'), -0.0013615733736762482),
 (((5, 18, 0), 'hit'), -0.0013574660633484162),
 (((6, 18, 0), 'hit'), -0.00145985401459854),
 (((7, 18, 0), 'hit'), -0.0012857142857142856),
 (((3, 18, 0), 'hit'), -0.0016474464579901153),
 (((9, 18, 1), 'hit'), -0.011250000000000001),
 (((2, 18, 1), 'hit'), -0.01139240506329114),
 (((1, 18, 1), 'hit'), -0.009000000000000001),
 (((10, 18, 1), 'hit'), -0.002341040462427746),
 (((5, 18, 1), 'hit'), -0.007673684210526317),
 (((7, 18, 1), 'hit'), -0.010945945945945947),
 (((8, 18, 1), 'hit'), -0.009642857142857144),
 (((4, 18, 1), 'hit'), -0.009101123595505618),
 (((6, 18, 1), 'hit'), -0.01139240506329114),
 (((3, 18, 1), 'hit'), -0.01),
 (((10, 19, 0), 'hit'), -0.0003785011355034065),
 (((6, 19, 0), 'hit'), -0.0016129032258064516),
 (((1, 19, 0), 'hit'), -0.0015479876160990713),
 (((7, 19, 0), 'hit'), -0.0014970059880239522),
 (((5, 19, 0), 'hit'), -0.00141287284144427),
 (((9, 19, 0), 'hit'), -0.0015455950540958269),
 (((8, 19, 0), 'hit'), -0.0014577259475218659),
 (((4, 19, 0), 'hit'), -0.0014705882352941176),
 (((3, 19, 0), 'hit'), -0.0015625),
 (((2, 19, 0), 'hit'), -0.001488095238095238),
 (((2, 19, 1), 'hit'), -0.006906315789473686),
 (((1, 19, 1), 'hit'), -0.010112359550561799),
 (((10, 19, 1), 'hit'), -0.00234375),
 (((4, 19, 1), 'hit'), -0.01),
 (((5, 19, 1), 'hit'), -0.006982758620689655),
 (((7, 19, 1), 'hit'), -0.008181818181818182),
 (((8, 19, 1), 'hit'), -0.00967741935483871),
 (((3, 19, 1), 'hit'), -0.010112359550561799),
 (((9, 19, 1), 'hit'), -0.010588235294117647),
 (((6, 19, 1), 'hit'), -0.010588235294117647),
 (((10, 20, 0), 'hit'), -0.0002702702702702703),
 (((1, 20, 0), 'hit'), -0.000992282249173098),
 (((7, 20, 0), 'hit'), -0.001091703056768559),
 (((9, 20, 0), 'hit'), -0.0011904761904761906),
 (((5, 20, 0), 'hit'), -0.0011350737797956867),
 (((4, 20, 0), 'hit'), -0.0010638297872340426),
 (((6, 20, 0), 'hit'), -0.0010905125408942203),
 (((3, 20, 0), 'hit'), -0.0009879253567508233),
 (((2, 20, 0), 'hit'), -0.0011049723756906078),
 (((8, 20, 0), 'hit'), -0.0010895883777239709),
 (((3, 20, 1), 'hit'), -0.008181818181818182),
 (((4, 20, 1), 'hit'), -0.006377952755905512),
 (((10, 20, 1), 'hit'), -0.002238805970149254),
 (((7, 20, 1), 'hit'), -0.009473684210526316),
 (((5, 20, 1), 'hit'), -0.007563025210084034),
 (((9, 20, 1), 'hit'), -0.007641509433962265),
 (((8, 20, 1), 'hit'), -0.009574468085106383),
 (((2, 20, 1), 'hit'), -0.00967741935483871),
 (((6, 20, 1), 'hit'), -0.007758620689655172),
 (((1, 20, 1), 'hit'), -0.00909090909090909),
 (((5, 21, 0), 'hit'), -0.0017482517482517483),
 (((9, 21, 0), 'hit'), -0.0016806722689075631),
 (((8, 21, 0), 'hit'), -0.0017123287671232876),
 (((2, 21, 0), 'hit'), -0.0018115942028985507),
 (((10, 21, 0), 'hit'), -0.00042918454935622315),
 (((3, 21, 0), 'hit'), -0.0017761989342806395),
 (((7, 21, 0), 'hit'), -0.0015923566878980893),
 (((6, 21, 0), 'hit'), -0.001584786053882726),
 (((1, 21, 0), 'hit'), -0.0015625),
 (((4, 21, 0), 'hit'), -0.0017241379310344827),
 (((4, 21, 1), 'hit'), -0.003474903474903475),
 (((2, 21, 1), 'hit'), -0.003515625),
 (((10, 21, 1), 'hit'), -0.0008797653958944282),
 (((7, 21, 1), 'hit'), -0.0035294117647058825),
 (((9, 21, 1), 'hit'), -0.0034090909090909094),
 (((5, 21, 1), 'hit'), -0.0031640625),
 (((8, 21, 1), 'hit'), -0.0036290322580645163),
 (((1, 21, 1), 'hit'), -0.0036734693877551023),
 (((6, 21, 1), 'hit'), -0.0033582089552238806),
 (((3, 21, 1), 'hit'), -0.0031395348837209304)]

In [366]:
for k, v in policy.items(): 
    if v != 'stick':
        print(k,v)